In [222]:
import pandas as pd
import numpy as np

In [223]:
WEAPON_COLUMNS = ['A1-weapon', 'A2-weapon', 'A3-weapon', 'A4-weapon', 'B1-weapon', 'B2-weapon', 'B3-weapon', 'B4-weapon']
RANK_COLUMNS = ['A1-rank', 'A2-rank', 'A3-rank', 'A4-rank', 'B1-rank', 'B2-rank', 'B3-rank', 'B4-rank']
LEVEL_COLUMNS = ['A1-level', 'A2-level', 'A3-level', 'A4-level', 'B1-level', 'B2-level', 'B3-level', 'B4-level']

In [224]:
train_data = pd.read_csv("data/train_data.csv", index_col="id")
test_data = pd.read_csv("data/test_data.csv", index_col="id")

In [225]:
train_data

period game-ver lobby-mode     lobby      mode  \
id                                                                         
1      2019-10-15T20:00:00+00:00    5.0.1    regular  standard  nawabari   
2      2019-12-14T04:00:00+00:00    5.0.1    regular  standard  nawabari   
3      2019-12-25T14:00:00+00:00    5.0.1      gachi  standard      hoko   
4      2019-11-11T14:00:00+00:00    5.0.1    regular  standard  nawabari   
5      2019-12-14T06:00:00+00:00    5.0.1      gachi  standard      hoko   
...                          ...      ...        ...       ...       ...   
66121  2019-10-11T10:00:00+00:00    5.0.1      gachi  standard      area   
66122  2019-12-04T00:00:00+00:00    5.0.1      gachi  standard     asari   
66123  2019-10-22T00:00:00+00:00    5.0.1      gachi  standard      hoko   
66124  2019-12-11T00:00:00+00:00    5.0.1      gachi  standard      area   
66125  2019-12-13T18:00:00+00:00    5.0.1      gachi  standard     asari   

           stage            A1-weapon A1-rank  A1-level           A2-weapon  \
id                                                                            
1        sumeshi      sshooter_becchu     NaN       139     soytuber_custom   
2        arowana  parashelter_sorella     NaN       198          jetsweeper   
3            ama               nzap89      a-       114    quadhopper_black   
4         engawa          bamboo14mk1     NaN       336  splatroller_becchu   
5        chozame               bold_7       x       299          hissen_hue   
...          ...                  ...     ...       ...                 ...   
66121      devon       hokusai_becchu       a        66            soytuber   
66122      otoro       hokusai_becchu      s+       204        prime_becchu   
66123      bbass        prime_collabo      a+       116       promodeler_rg   
66124  fujitsubo   heroroller_replica      s+       210           sharp_neo   
66125    sumeshi          splatroller       s       132              nzap85   

       ...           B2-weapon  B2-rank B2-level            B3-weapon  \
id     ...                                                              
1      ...      hokusai_becchu      NaN     26.0  herocharger_replica   
2      ...         squiclean_b      NaN    118.0       campingshelter   
3      ...              nzap85       a+    163.0         prime_becchu   
4      ...             liter4k      NaN    189.0        promodeler_mg   
5      ...        sputtery_hue        x     45.0   bucketslosher_soda   
...    ...                 ...      ...      ...                  ...   
66121  ...              nzap85       a+    272.0         splatcharger   
66122  ...        prime_becchu       s+    167.0                pablo   
66123  ...            bold_neo       a+     70.0               nzap85   
66124  ...  heroroller_replica       s+    395.0     rapid_elite_deco   
66125  ...              nzap85        s    124.0            l3reelgun   

       B3-rank B3-level           B4-weapon  B4-rank B4-level  y  
id                                                                
1          NaN     68.0           sharp_neo      NaN     31.0  1  
2          NaN    168.0      sputtery_clear      NaN    151.0  0  
3           a-    160.0  dualsweeper_custom        a    126.0  0  
4          NaN    194.0   hotblaster_custom      NaN    391.0  0  
5            x    246.0              wakaba        x    160.0  1  
...        ...      ...                 ...      ...      ... ..  
66121        a     38.0              wakaba       a+    283.0  1  
66122       s+    188.0              nzap89       s+    170.0  1  
66123       a+    191.0          hissen_hue       a+    139.0  1  
66124       s+    223.0           sharp_neo       s+    194.0  0  
66125        s    103.0      hokusai_becchu        s     35.0  0  

[66125 rows x 31 columns]

## 欠損値補完

In [226]:
def complete(data):
    for col_name in WEAPON_COLUMNS:
        data[col_name] = data[col_name].fillna('NULL')
    for col_name in LEVEL_COLUMNS:
        data[col_name] = data[col_name].fillna(0)
    for col_name in RANK_COLUMNS:
        data[col_name] = data[col_name].fillna('n')

In [227]:
complete(train_data)
complete(test_data)

## エンコーダー

In [228]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelBinarizer

In [229]:
train_data["mode"].unique().reshape(-1, 1)

array([['nawabari'],
       ['hoko'],
       ['yagura'],
       ['area'],
       ['asari']], dtype=object)

### Mode

In [230]:
# TODO: sparseをTrueにする？
mode_encoder = LabelBinarizer()
mode_encoder.fit(train_data["mode"].unique())

LabelBinarizer()

In [231]:
def make_mode(data):
    return pd.DataFrame(mode_encoder.transform(data), columns=mode_encoder.classes_)

### Stage

In [232]:
stage_encoder = LabelBinarizer()
stage_encoder.fit(train_data["stage"].unique())
def make_stage(data):
    return pd.DataFrame(stage_encoder.transform(data), columns=stage_encoder.classes_)

In [233]:
make_stage(train_data["stage"])

ajifry  ama  anchovy  arowana  battera  bbass  chozame  devon  engawa  \
0           0    0        0        0        0      0        0      0       0   
1           0    0        0        1        0      0        0      0       0   
2           0    1        0        0        0      0        0      0       0   
3           0    0        0        0        0      0        0      0       1   
4           0    0        0        0        0      0        1      0       0   
...       ...  ...      ...      ...      ...    ...      ...    ...     ...   
66120       0    0        0        0        0      0        0      1       0   
66121       0    0        0        0        0      0        0      0       0   
66122       0    0        0        0        0      1        0      0       0   
66123       0    0        0        0        0      0        0      0       0   
66124       0    0        0        0        0      0        0      0       0   

       fujitsubo  ...  kombu  manta  mongara  mozuku  mutsugoro  otoro  \
0              0  ...      0      0        0       0          0      0   
1              0  ...      0      0        0       0          0      0   
2              0  ...      0      0        0       0          0      0   
3              0  ...      0      0        0       0          0      0   
4              0  ...      0      0        0       0          0      0   
...          ...  ...    ...    ...      ...     ...        ...    ...   
66120          0  ...      0      0        0       0          0      0   
66121          0  ...      0      0        0       0          0      1   
66122          0  ...      0      0        0       0          0      0   
66123          1  ...      0      0        0       0          0      0   
66124          0  ...      0      0        0       0          0      0   

       shottsuru  sumeshi  tachiuo  zatou  
0              0        1        0      0  
1              0        0        0      0  
2              0        0        0      0  
3              0        0        0      0  
4              0        0        0      0  
...          ...      ...      ...    ...  
66120          0        0        0      0  
66121          0        0        0      0  
66122          0        0        0      0  
66123          0        0        0      0  
66124          0        1        0      0  

[66125 rows x 23 columns]

### Weapon
全部で140種類？

In [234]:
weapon_encoder = LabelBinarizer()
all_weapons = pd.concat([train_data[x] for x in WEAPON_COLUMNS]).dropna().unique()
weapon_encoder.fit(all_weapons)

LabelBinarizer()

In [235]:
def make_weapon(data):
    return pd.DataFrame(weapon_encoder.transform(data), columns=weapon_encoder.classes_)

### Rank
手動で決めてしまう

In [236]:
# TODO: 感覚で数字つけておく
rank_map = {'n': 0, 'c-': 1, 'c': 2, 'c+': 3, 'b-': 4, 'b': 5, 'b+': 6, 'a-': 7, 'a': 8, 'a+': 9, 's': 10, 's+': 11, 'x': 12}
def encode_rank(rank):
    try:
        return rank_map[rank]
    except KeyError:
        return 0

## 標準化

### Level

In [237]:
from sklearn.preprocessing import StandardScaler

In [238]:
level_scaler = StandardScaler()

In [239]:
levels = np.concatenate([train_data[x].values for x in LEVEL_COLUMNS], axis=0).reshape(-1, 1)
level_scaler.fit(levels)

StandardScaler()

In [240]:
level_scaler.transform([[200]])

array([[0.38124705]])

### Rank

In [241]:
rank_scaler = StandardScaler()

In [242]:
rank_mapper = np.vectorize(encode_rank)

In [243]:
rank_scaler = rank_scaler.fit(rank_mapper(np.concatenate([train_data[x].values for x in RANK_COLUMNS], axis=0)).reshape(-1, 1))

In [244]:
rank_scaler.transform([[21]])

array([[2.66136804]])

## データ作成

In [245]:
# nawabariとそれ意外で違う値
def make_weapon_bias(data, player):
    weapon_col = player + '-weapon'
    level_col = player + '-level'
    rank_col = player + '-rank'
    
    weapon_data = make_weapon(data[weapon_col])
    
    # nawabariなら1,それ意外は0
    nawabari_data = np.where(data['mode'] == 'nawabari', 1, 0).reshape(-1, 1)
    level_data = level_scaler.transform(data[level_col].values.reshape(-1, 1)) * nawabari_data
    
    # nawabariなら0,それ意外は1
    nawabari_inv_data = nawabari_data * -1 + 1
    rank_data = rank_scaler.transform(rank_mapper(data['A1-rank']).reshape(-1, 1)) * nawabari_inv_data
    weapon_data = weapon_data.values * (level_data + rank_data)
    return pd.DataFrame(weapon_data, columns=weapon_encoder.classes_)

In [246]:
make_weapon_bias(train_data[0:3], 'A1')

52gal  52gal_becchu  52gal_deco  96gal  96gal_deco  NULL  bamboo14mk1  \
0   -0.0          -0.0        -0.0   -0.0        -0.0  -0.0         -0.0   
1    0.0           0.0         0.0    0.0         0.0   0.0          0.0   
2   -0.0          -0.0        -0.0   -0.0        -0.0  -0.0         -0.0   

   bamboo14mk2  bamboo14mk3  barrelspinner  ...  spygadget_sorella  \
0         -0.0         -0.0           -0.0  ...               -0.0   
1          0.0          0.0            0.0  ...                0.0   
2         -0.0         -0.0           -0.0  ...               -0.0   

   squiclean_a  squiclean_b  squiclean_g  sshooter  sshooter_becchu  \
0         -0.0         -0.0         -0.0      -0.0        -0.225176   
1          0.0          0.0          0.0       0.0         0.000000   
2         -0.0         -0.0         -0.0      -0.0        -0.000000   

   sshooter_collabo  variableroller  variableroller_foil  wakaba  
0              -0.0            -0.0                 -0.0    -0.0  
1               0.0             0.0                  0.0     0.0  
2              -0.0            -0.0                 -0.0    -0.0  

[3 rows x 140 columns]

In [247]:
rank_scaler.transform(rank_mapper(train_data['A1-rank']).reshape(-1, 1))

array([[-1.77430725],
       [-1.77430725],
       [-0.29574882],
       ...,
       [ 0.12669645],
       [ 0.54914171],
       [ 0.33791908]])

In [263]:
def make_data(data, with_y=False):
    mode_data = make_mode(train_data['mode'])
    stage_data = make_stage(train_data['stage'])
    a_data = make_weapon_bias(data, 'A1') + make_weapon_bias(data, 'A2') + make_weapon_bias(data, 'A3') + make_weapon_bias(data, 'A4')
    b_data = make_weapon_bias(data, 'B1') + make_weapon_bias(data, 'B2') + make_weapon_bias(data, 'B3') + make_weapon_bias(data, 'B4')
    X = pd.concat([mode_data, stage_data, a_data, b_data], axis=1)
    if with_y:
        y = data['y']
        return X, y
    return X

In [264]:
train_X, train_y = make_data(train_data, with_y=True)

In [265]:
test_X = make_data(test_data)

In [269]:
train_X.head()

area  asari  hoko  nawabari  yagura  ajifry  ama  anchovy  arowana  \
0     0      0     0         1       0       0    0        0        0   

   battera  ...  spygadget_sorella  squiclean_a  squiclean_b  squiclean_g  \
0        0  ...               -0.0         -0.0         -0.0         -0.0   

   sshooter  sshooter_becchu  sshooter_collabo  variableroller  \
0      -0.0             -0.0              -0.0            -0.0   

   variableroller_foil  wakaba  
0                 -0.0    -0.0  

[1 rows x 308 columns]

## 学習

## テスト

In [1]:
from datetime import datetime

In [2]:
dtest = xgb.DMatrix(test_X)

NameError: name 'xgb' is not defined

In [3]:
test_pred_proba = model.predict(dtest)

NameError: name 'model' is not defined

In [30]:
test_pred = np.where(test_pred_proba > 0.5, 1, 0)

In [4]:
submit_df = pd.DataFrame({'y': test_pred})
submit_df.index.name = 'id'
submit_df.to_csv('submission_{}.csv', datetime.now().format("%Y%m%d_%H%M%S"))

NameError: name 'pd' is not defined